name: shorty

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: ghcr.io/rosowskimik/shorty-server
    environment:
      SERVER_DATABASE: redis://db
    depends_on:
      db:
        condition: service_started

  db:
    image: redis:alpine
    ports:
      - 6379:6379
