name: shorty

services:
  server:
    build: .
    image: ghcr.io/rosowskimik/shorty
    ports:
      - 3000:80
    environment:
      APP_DB: redis://db
      APP_PUB_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_started

  db:
    image: redis:alpine
    ports:
      - 6379:6379
