apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ghcr.io/rosowskimik/shorty-client:latest
        ports:
        - containerPort: 8080
          name: client-port
        env:
        - name: LEPTOS_SITE_ADDR
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: client-address
        - name: CLIENT_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: client-public-url
        - name: CLIENT_GRPC_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: grpc-endpoint
        - name: CLIENT_GRPC_TOKEN
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: server-token
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: client-port
      nodePort: 30100

