apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: redis-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
  volumeName: redis-pv
