apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: eqalpha/keydb:x86_64_v6.3.4
        args:
          - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis-conf
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-conf
        configMap:
          name: redis-config
          items:
            - key: redis.conf
              path: redis.conf
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
spec:
  selector:
    app: redis-master
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-port
