apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-master-url: redis://redis-master-service
  redis-replica-url: redis://redis-replica-service
  redis.conf: |
    appendonly no
    protected-mode no
  redis.conf.replica: |
    appendonly no
    protected-mode no
    slaveof redis-master-service.default.svc.cluster.local 6379
