apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/rosowskimik/shorty-server:v0.2.1
        ports:
        - containerPort: 50001
          name: server-port
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 250m
        env:
        - name: SERVER_BIND_IP
          value: "::"
        - name: SERVER_LOG
          value: info
        - name: SERVER_DATABASE
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-master-url
        - name: SERVER_DATABASE_REPLICA
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-replica-url
        - name: SERVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: server-token
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 50001
      targetPort: server-port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
