name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CLIENT: ${{ github.repository }}-client
  IMAGE_NAME_SERVER: ${{ github.repository }}-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # For image signing

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3.4.0

      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Log into ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Generate metadata for client image
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_CLIENT }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      -
        name: Generate metadata for server image
        id: meta-server
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      -
        name: Build & push client image
        id: build-and-push-client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.client
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Build & push server image
        id: build-and-push-server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.server
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      -
        name: Sign published Docker images
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS_CLIENT: ${{ steps.meta-client.outputs.tags }}
          DIGEST_CLIENT: ${{ steps.build-and-push-client.outputs.digest }}
          TAGS_SERVER: ${{ steps.meta-server.outputs.tags }}
          DIGEST_SERVER: ${{ steps.build-and-push-server.outputs.digest }}
        run: |
          echo "${TAGS_CLIENT}" | xargs -I {} cosign sign --yes {}@${DIGEST_CLIENT}
          echo "${TAGS_SERVER}" | xargs -I {} cosign sign --yes {}@${DIGEST_SERVER}
